from django.shortcuts import render
from django.http import HttpResponse
from django import forms
import json
import traceback
from io import StringIO
import sys
import csv
import os

#Homepage when one initially visits the site!
def home(request):
	return HttpResponse("Placeholder text for the homepage")

#Classes and functions to generate the quiz form and output results
def quiz_form(request):
	context = {}
	res = None
	if request.method == 'GET':
		form = QuizForm(request.GET)

		if form.is_valid()

def _is_valid(res):
	"""
	Ensures that the response from the quiz form will match the input required by survey.py

	"""
	return []



def _build_dropdown(options):
	"""
	Converts a list to a tuple with format (value, caption)

	"""
	return[(x,x) if x is not None else ('', NOPREF_STR) for x \
	in options]


#Dropdown configuration lists
MARRAIGE = _build_dropdown(['Single', 'Married', 'Other'])
STABILITY = _build_dropdown(['Strongly agree', 'Somewhat agree,',\
 'Somewhat disagree', 'Strongly disagree'])
GOALS = _build_dropdown(['Generating income', 'Growing wealth', \
	'Other'])
PRIORITIES = _build_dropdown(['Maximizing gains', 'Minimizing losses', 'Both equally'])
DIVESTMENT = _build_dropdown(['A few months', '1-3 years', '3-5 years', '5-10 years', 'More than 10 years'])
CHANCE = _build_dropdown(['$1000 @ 100%  chance', '$5000 @ 50%  chance', '$100,000 @ 5%  chance'])
PANIC = _build_dropdown(['Sell everything', 'Sell some stocks', 'Do nothing', 'Buy more stocks'])




class MultipleChoice(forms.MultiValueField):
	def __init__(self, name, options):
		fields=(forms.ChoiceField(label=name, choices=options, required=True))



class QuizForm(forms.Form):
	how_old = forms.CharField(
		label='How old are you?',
		help_text='Please enter a number between 1 and 100',
		required=True)
	when_retire = forms.CharField(
		label='At what age do you plan to retire?'
		help_text='Please enter a number between 1 and 100 and \
		greater than your answer to Question 1',
		required=True)
	marital_status = MultipleChoice(
		label='What is your marital status?'
		help_text='Please select your status from the drop down \
		menu'
		required=True,
		widget=forms.widgets.MultiWidget(widgets=\
			(forms.widgets.Select(choices=MARRAIGE))))
	annual_income = forms.CharField(
		label='What is your annual income?',
		help_text='Please enter your gross income in U.S. dollars',
		required=True)
	income_stability = MultipleChoice(
		label='My current and future income sources are very stable',
		help_text='Select the statement with which you agree most',
		widget=forms.widgets.MultiWidget(widgets=forms.widgets.\
			Select(choices=STABILITY)))
	main_goal = MultipleChoice(
		label='What is your main goal in investing?',
		help_text='Choose the statement that best describes your \
		investment goal',
		widget=forms.MultiWidget(widgets=forms.widgets.Select\
			(choices=GOALS)))
	most_important = MultipleChoice(
		label='Which is more important to you?',
		help_text='Choose an option',
		widget=forms.MultiWidget(widgets=forms.widgets.Select\
			(choices=PRIORITIES)))
	divest_in = MultipleChoice(
		label='When do you plan to begin using money from your \
		investments?',
		help_text='Select a timeframe below',
		widget=forms.MultiWidget(widgets=forms.widgets.Select(choices=DIVESTMENT)))
	game_show = MultipleChoice(
		label='You are on a game show and given the choice \
		between receiving $1000, a 50%  chance to win $5,000,\
		or a 5%  chance to win $100,000. Which do you pick?',
		help_text='choose one option given the the scenario above',
		widget=forms.MultiWidget(widgets=forms.widgets.Select(choices=CHANCE)))
	stock_panic = MultipleChoice(
		label='The stock market drops 10%  over the course of \
		one month. What do you do?',
		help_text='select the option that best describes \
		your decision'
		widget=forms.MultiWidget(widgets=forms.widgets.Select(choices=PANIC)))








	return HttpResponse("This will be the quiz page, generated by an http template")


# Create your views here.
