# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 04:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='freeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_response', models.TextField(blank=True, max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='multipleChoiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='choice_index',
        ),
        migrations.AddField(
            model_name='choice',
            name='multi1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='multi2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='multi3',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='multi4',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='multi5',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='multiplechoiceresponse',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='multiplechoiceresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.AddField(
            model_name='multiplechoiceresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
